### ISSUE TITLE
undefined error after upgrading to 0.4.8

### ISSUE THREAD

**Issue by factualz** [CollectionFS/Meteor-CollectionFS#274]
/home/action/.meteor/tools/c2a0453c51/lib/node_modules/fibers/future.js:173  
W20140410-07:45:45.152(0)? (STDERR)                                             throw(ex);  
W20140410-07:45:45.153(0)? (STDERR)                                                   ^  
W20140410-07:45:45.153(0)? (STDERR) TypeError: undefined is not a function  
W20140410-07:45:45.153(0)? (STDERR)     at app/lib/app/model.js:18:44

----------- the line in code where error is pointed at ---------
Docs = new FS.Collection('docs', {stores: [new FS.Store.GridFS('docs')]});
Photos = new FS.Collection('photos', {stores: [new FS.Store.GridFS('photos')]});
