### ISSUE TITLE
Images not displaying after upgrading to 4.8

### ISSUE THREAD

**Issue by chathuraa** [CollectionFS/Meteor-CollectionFS#300]
I get the following Error.

Exception from Deps recompute function: TypeError: string is not a function
    at FS.File.url (http://localhost:3000/packages/cfs-access-point.js?e83dc55947bb1511a58df06a1efb67c4ce583fc9:127:25)
    at Object.Template.watchList.helpers.auction (http://localhost:3000/client/views/watch_list/watch_list.js?100b8af54aacef141ee0a21364b6d56949b6c475:40:30)
    at http://localhost:3000/packages/blaze-layout.js?58621fa8e3ed65d10240815d5ba3fb34e2e9fdc5:520:21
    at Object.Spacebars.call (http://localhost:3000/packages/spacebars.js?f49560fc90a8d71b7637d9596696078881b8c812:173:18)
    at HTML.TR.Spacebars.With.UI.block.self (http://localhost:3000/client/views/watch_list/template.watch_list.js?9f4550f57f3ca9f4b150db38a9333dcb1922ed32:12:24)
    at http://localhost:3000/packages/ui.js?f0696b7e9407b8f11e5838e7e7820e9b6d7fc92f:2088:23
    at callWithNoYieldsAllowed (http://localhost:3000/packages/deps.js?91f1235baecd83915f7d3a7328526dbba41482be:87:5)
    at _assign._compute (http://localhost:3000/packages/deps.js?91f1235baecd83915f7d3a7328526dbba41482be:225:7)
    at new Deps.Computation (http://localhost:3000/packages/deps.js?91f1235baecd83915f7d3a7328526dbba41482be:157:10)
    at Object._assign.autorun (http://localhost:3000/packages/deps.js?91f1235baecd83915f7d3a7328526dbba41482be:377:13) 

This is my code.
Template.watchList.helpers({
    watchedAuction: function() {
        var auctions = WatchLists.find({
            user_id: Meteor.userId(),
            watching: true
        });
        return auctions;
    },
    auction: function() {
        var auction = Auctions.findOne({
            _id: this.auction_id
        });
        auction.product = Products.findOne({
            _id: auction.productID
        });
        var currentTime = auction.currentTime; //Number(moment(Session.get('time')).valueOf());
        var endDate = auction.extendedEndDate;
        var timeTo = endDate - currentTime;
        if (timeTo > 0) {
            var tr = msToMoment(timeTo);
        } else {
            var tr = msToMoment(0);
        }
        var product = Products.findOne({
            _id: auction.productID
        })
        var images = product.imgs;
        var imgID = images[0]._id;
        var img = Images.findOne({
            _id: imgID
        });
        auction.imgurl = img.url();
        auction.bestBidString = numeral(auction.bestBid / 100).format('$0,0.00');
        _.extend(auction, countdown(auction));
        if (auction.newbid) {
            auction.newbidregistered = 'newbid';
        }
        return auction;
    },
});
any help would be greatly appreciated
